backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

locale: 'de'

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "../../assets/images" # The src attribute for uploaded media

collections:
  - name: "Neuigkeiten" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/neues" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Datum", name: "pubDate", widget: "datetime" }
      - { label: "Artikelbild", name: "src", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }